import { Product } from '../App';

export const products: Product[] = [
  // Living Room Furniture
  {
    id: '1',
    name: 'Modern Velvet Sofa',
    price: 89999,
    image: 'https://images.unsplash.com/photo-1763565909003-46e9dfb68a00?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBzb2ZhJTIwZnVybml0dXJlfGVufDF8fHx8MTc2NTY2Njk4NXww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Living Room Furniture',
    subcategory: 'Seating',
    itemType: 'Sofas (3-seater)',
    description: 'Luxurious velvet sofa with deep cushions and modern design. Perfect for contemporary living spaces.',
    rating: 4.8,
    reviews: 124,
  },
  {
    id: '7',
    name: 'Glass Coffee Table',
    price: 22999,
    image: 'https://images.unsplash.com/photo-1542372147193-a7aca54189cd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2ZmZWUlMjB0YWJsZXxlbnwxfHx8fDE3NjU2ODgzMDZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Living Room Furniture',
    subcategory: 'Tables',
    itemType: 'Coffee Tables',
    description: 'Elegant glass coffee table with metal frame. Adds sophistication to any living room.',
    rating: 4.6,
    reviews: 143,
  },
  {
    id: '8',
    name: 'Accent Armchair',
    price: 32999,
    image: 'https://images.unsplash.com/photo-1714872245785-674ae3038d21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcm1jaGFpciUyMGxpdmluZyUyMHJvb218ZW58MXx8fHwxNzY1NjQ1ODUyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Living Room Furniture',
    subcategory: 'Seating',
    itemType: 'Accent Chairs',
    description: 'Stylish accent chair with plush cushioning. Perfect for reading nooks or living rooms.',
    rating: 4.7,
    reviews: 167,
  },
  {
    id: '9',
    name: 'L-Shaped Sectional Sofa',
    price: 125999,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsc2hhcGVkJTIwc29mYXxlbnwxfHx8fDE3MzQ5Nzk0MDR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Living Room Furniture',
    subcategory: 'Seating',
    itemType: 'L-Shaped Sofas',
    description: 'Spacious L-shaped sectional perfect for large living rooms. Premium fabric with extra cushioning.',
    rating: 4.9,
    reviews: 98,
  },
  {
    id: '12',
    name: 'TV Unit with Storage',
    price: 42999,
    image: 'https://images.unsplash.com/photo-1594026112284-02bb6f3352fe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0diUyMHVuaXQlMjBmdXJuaXR1cmV8ZW58MXx8fHwxNzM0OTc5NDUyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Living Room Furniture',
    subcategory: 'Entertainment',
    itemType: 'TV Units',
    description: 'Contemporary TV unit with multiple storage compartments. Cable management included.',
    rating: 4.7,
    reviews: 189,
  },
  {
    id: '13',
    name: 'Luxury Recliner Chair',
    price: 54999,
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZWNsaW5lciUyMGNoYWlyfGVufDF8fHx8MTczNDk3OTUyMXww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Living Room Furniture',
    subcategory: 'Seating',
    itemType: 'Recliners',
    description: 'Premium leather recliner with adjustable positions. Ultimate comfort for relaxation.',
    rating: 4.8,
    reviews: 156,
  },
  {
    id: '14',
    name: 'Marble Console Table',
    price: 38999,
    image: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb25zb2xlJTIwdGFibGV8ZW58MXx8fHwxNzM0OTc5NTM2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Living Room Furniture',
    subcategory: 'Tables',
    itemType: 'Console Tables',
    description: 'Elegant marble-top console table with gold metal base. Perfect for entryways.',
    rating: 4.5,
    reviews: 92,
  },
  {
    id: '15',
    name: 'Ottoman Storage Bench',
    price: 18999,
    image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvdHRvbWFuJTIwYmVuY2h8ZW58MXx8fHwxNzM0OTc5NTUxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Living Room Furniture',
    subcategory: 'Seating',
    itemType: 'Ottomans',
    description: 'Multifunctional ottoman with hidden storage. Upholstered in premium fabric.',
    rating: 4.6,
    reviews: 134,
  },

  // Bedroom Furniture
  {
    id: '4',
    name: 'Platform Bed Frame',
    price: 45999,
    image: 'https://images.unsplash.com/photo-1680503146476-abb8c752e1f4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZWRyb29tJTIwZnVybml0dXJlfGVufDF8fHx8MTc2NTY1OTQ1N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Bedroom Furniture',
    subcategory: 'Beds',
    itemType: 'Queen Beds',
    description: 'Contemporary platform bed with upholstered headboard. Available in Queen and King sizes.',
    rating: 4.7,
    reviews: 156,
  },
  {
    id: '11',
    name: 'Sliding Wardrobe',
    price: 78999,
    image: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3YXJkcm9iZSUyMGZ1cm5pdHVyZXxlbnwxfHx8fDE3MzQ5Nzk0Mzd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Bedroom Furniture',
    subcategory: 'Storage',
    itemType: 'Wardrobes (Sliding)',
    description: 'Modern sliding wardrobe with mirror finish and ample storage space. Space-saving design.',
    rating: 4.6,
    reviews: 145,
  },
  {
    id: '16',
    name: 'King Size Bed with Storage',
    price: 68999,
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxraW5nJTIwYmVkfGVufDF8fHx8MTczNDk3OTU2N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Bedroom Furniture',
    subcategory: 'Beds',
    itemType: 'Hydraulic Storage Beds',
    description: 'King-size hydraulic storage bed with gas lift mechanism. Maximizes bedroom space.',
    rating: 4.9,
    reviews: 178,
  },
  {
    id: '17',
    name: 'Wooden Dressing Table',
    price: 35999,
    image: 'https://images.unsplash.com/photo-1615529182904-14819c35db37?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkcmVzc2luZyUyMHRhYmxlfGVufDF8fHx8MTczNDk3OTU4Mnww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Bedroom Furniture',
    subcategory: 'Storage',
    itemType: 'Dressing Tables',
    description: 'Elegant dressing table with large mirror and multiple drawers. Classic design.',
    rating: 4.7,
    reviews: 123,
  },
  {
    id: '18',
    name: 'Bedside Table Set',
    price: 24999,
    image: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZWRzaWRlJTIwdGFibGV8ZW58MXx8fHwxNzM0OTc5NTk3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Bedroom Furniture',
    subcategory: 'Storage',
    itemType: 'Bedside Tables',
    description: 'Set of 2 matching bedside tables with drawers. Perfect for bedroom organization.',
    rating: 4.5,
    reviews: 167,
  },
  {
    id: '19',
    name: 'Kids Bunk Bed',
    price: 52999,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidW5rJTIwYmVkfGVufDF8fHx8MTczNDk3OTYxMnww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Bedroom Furniture',
    subcategory: 'Beds',
    itemType: 'Bunk Beds',
    description: 'Sturdy wooden bunk bed with safety rails. Ideal for kids rooms and guest rooms.',
    rating: 4.8,
    reviews: 145,
  },

  // Dining & Kitchen Furniture
  {
    id: '2',
    name: 'Minimalist Dining Chair',
    price: 12999,
    image: 'https://images.unsplash.com/photo-1715618368833-752c6b65f51b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaW5pbWFsaXN0JTIwY2hhaXJ8ZW58MXx8fHwxNzY1NjkyNDMzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Dining & Kitchen Furniture',
    subcategory: 'Dining',
    itemType: 'Dining Chairs',
    description: 'Sleek and comfortable dining chair with clean lines. Sold individually.',
    rating: 4.6,
    reviews: 87,
  },
  {
    id: '3',
    name: 'Wooden Dining Table',
    price: 65999,
    image: 'https://images.unsplash.com/photo-1758977403438-1b8546560d31?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b29kZW4lMjBkaW5pbmclMjB0YWJsZXxlbnwxfHx8fDE3NjU3MDU4NjF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Dining & Kitchen Furniture',
    subcategory: 'Dining',
    itemType: 'Dining Tables (6-seater)',
    description: 'Solid wood dining table with natural finish. Seats 6-8 people comfortably.',
    rating: 4.9,
    reviews: 203,
  },
  {
    id: '20',
    name: '4-Seater Dining Set',
    price: 48999,
    image: 'https://images.unsplash.com/photo-1617806118233-18e1de247200?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkaW5pbmclMjBzZXR8ZW58MXx8fHwxNzM0OTc5NjI3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Dining & Kitchen Furniture',
    subcategory: 'Dining',
    itemType: 'Dining Tables (4-seater)',
    description: 'Complete 4-seater dining set with table and chairs. Perfect for small families.',
    rating: 4.7,
    reviews: 234,
  },
  {
    id: '21',
    name: 'Bar Stool Set',
    price: 19999,
    image: 'https://images.unsplash.com/photo-1551298370-9d3d53740c72?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXIlMjBzdG9vbHxlbnwxfHx8fDE3MzQ5Nzk2NDJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Dining & Kitchen Furniture',
    subcategory: 'Dining',
    itemType: 'Bar Stools',
    description: 'Set of 2 modern bar stools with adjustable height. Chrome finish.',
    rating: 4.5,
    reviews: 98,
  },
  {
    id: '22',
    name: 'Kitchen Island Cart',
    price: 44999,
    image: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxraXRjaGVuJTIwaXNsYW5kfGVufDF8fHx8MTczNDk3OTY1N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Dining & Kitchen Furniture',
    subcategory: 'Kitchen',
    itemType: 'Kitchen Islands',
    description: 'Mobile kitchen island with storage and granite top. Versatile and functional.',
    rating: 4.8,
    reviews: 167,
  },
  {
    id: '23',
    name: 'Crockery Display Cabinet',
    price: 56999,
    image: 'https://images.unsplash.com/photo-1595428774223-ef52624120d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjcm9ja2VyeSUyMGNhYmluZXR8ZW58MXx8fHwxNzM0OTc5NjcyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Dining & Kitchen Furniture',
    subcategory: 'Dining',
    itemType: 'Crockery Units',
    description: 'Glass-front crockery cabinet with LED lighting. Showcase your fine china.',
    rating: 4.6,
    reviews: 112,
  },

  // Office & Study Furniture
  {
    id: '5',
    name: 'Executive Office Desk',
    price: 35999,
    image: 'https://images.unsplash.com/photo-1513530534585-c7b1394c6d51?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvZmZpY2UlMjBkZXNrfGVufDF8fHx8MTc2NTYzOTgwMHww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Office & Study Furniture',
    subcategory: 'Desks',
    itemType: 'Executive Desks',
    description: 'Spacious office desk with cable management. Perfect for home office setups.',
    rating: 4.5,
    reviews: 92,
  },
  {
    id: '6',
    name: 'Modern Bookshelf',
    price: 28999,
    image: 'https://images.unsplash.com/photo-1747928272448-49524fcb5cfb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxib29rc2hlbGYlMjBtb2Rlcm58ZW58MXx8fHwxNzY1NzA1ODYyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Office & Study Furniture',
    subcategory: 'Storage',
    itemType: 'Bookcases',
    description: 'Five-tier bookshelf with modern design. Ideal for books, plants, and decorative items.',
    rating: 4.4,
    reviews: 78,
  },
  {
    id: '10',
    name: 'Ergonomic Office Chair',
    price: 18999,
    image: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlcmdvbm9taWMlMjBjaGFpcnxlbnwxfHx8fDE3MzQ5Nzk0MjJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Office & Study Furniture',
    subcategory: 'Seating',
    itemType: 'Ergonomic Chairs',
    description: 'Premium ergonomic chair with lumbar support and adjustable armrests. All-day comfort guaranteed.',
    rating: 4.8,
    reviews: 234,
  },
  {
    id: '24',
    name: 'L-Shaped Computer Desk',
    price: 42999,
    image: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb21wdXRlciUyMGRlc2t8ZW58MXx8fHwxNzM0OTc5Njg3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Office & Study Furniture',
    subcategory: 'Desks',
    itemType: 'Computer Tables',
    description: 'L-shaped computer desk with ample workspace. Ideal for multi-monitor setups.',
    rating: 4.7,
    reviews: 189,
  },
  {
    id: '25',
    name: 'Standing Desk Adjustable',
    price: 54999,
    image: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdGFuZGluZyUyMGRlc2t8ZW58MXx8fHwxNzM0OTc5NzAyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Office & Study Furniture',
    subcategory: 'Desks',
    itemType: 'Standing Desks',
    description: 'Electric height-adjustable standing desk. Promotes better posture and health.',
    rating: 4.9,
    reviews: 276,
  },
  {
    id: '26',
    name: 'Gaming Chair Pro',
    price: 24999,
    image: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnYW1pbmclMjBjaGFpcnxlbnwxfHx8fDE3MzQ5Nzk3MTd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Office & Study Furniture',
    subcategory: 'Seating',
    itemType: 'Gaming Chairs',
    description: 'Professional gaming chair with RGB lighting and 4D armrests. Maximum comfort.',
    rating: 4.8,
    reviews: 312,
  },
  {
    id: '27',
    name: 'Study Table with Shelves',
    price: 21999,
    image: 'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdHVkeSUyMHRhYmxlfGVufDF8fHx8MTczNDk3OTczMnww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Office & Study Furniture',
    subcategory: 'Desks',
    itemType: 'Study Tables',
    description: 'Compact study table with built-in shelving. Perfect for students and small spaces.',
    rating: 4.6,
    reviews: 198,
  },
  {
    id: '28',
    name: 'Filing Cabinet 3-Drawer',
    price: 16999,
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmaWxpbmclMjBjYWJpbmV0fGVufDF8fHx8MTczNDk3OTc0N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Office & Study Furniture',
    subcategory: 'Storage',
    itemType: 'Filing Cabinets',
    description: 'Metal filing cabinet with lock. Organize your important documents securely.',
    rating: 4.5,
    reviews: 156,
  },
  {
    id: '29',
    name: 'Conference Table 8-Seater',
    price: 89999,
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb25mZXJlbmNlJTIwdGFibGV8ZW58MXx8fHwxNzM0OTc5NzYyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Office & Study Furniture',
    subcategory: 'Seating',
    itemType: 'Conference Tables',
    description: 'Large conference table with cable management. Perfect for meeting rooms.',
    rating: 4.7,
    reviews: 89,
  },
  {
    id: '30',
    name: 'Reception Desk Modern',
    price: 72999,
    image: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZWNlcHRpb24lMjBkZXNrfGVufDF8fHx8MTczNDk3OTc3N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Office & Study Furniture',
    subcategory: 'Desks',
    itemType: 'Reception Desks',
    description: 'Sleek reception desk with LED lighting. Makes a great first impression.',
    rating: 4.8,
    reviews: 134,
  },

  // Outdoor & Garden Furniture
  {
    id: '31',
    name: 'Garden Patio Set',
    price: 64999,
    image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67def?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXRpbyUyMHNldHxlbnwxfHx8fDE3MzQ5Nzk3OTJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Outdoor & Garden Furniture',
    subcategory: 'Seating',
    itemType: 'Patio Sets',
    description: 'Weather-resistant patio set with 4 chairs and table. Perfect for outdoor entertaining.',
    rating: 4.7,
    reviews: 145,
  },
  {
    id: '32',
    name: 'Wooden Swing Jhula',
    price: 38999,
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnYXJkZW4lMjBzd2luZ3xlbnwxfHx8fDE3MzQ5Nzk4MDd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Outdoor & Garden Furniture',
    subcategory: 'Seating',
    itemType: 'Swings (Jhula)',
    description: 'Traditional wooden jhula with cushions. Add charm to your garden or balcony.',
    rating: 4.9,
    reviews: 187,
  },
  {
    id: '33',
    name: 'Sun Lounger Recliner',
    price: 28999,
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdW4lMjBsb3VuZ2VyfGVufDF8fHx8MTczNDk3OTgyMnww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Outdoor & Garden Furniture',
    subcategory: 'Seating',
    itemType: 'Loungers',
    description: 'Adjustable sun lounger with padded cushion. Perfect for poolside relaxation.',
    rating: 4.6,
    reviews: 123,
  },

  // Commercial & Institutional
  {
    id: '34',
    name: 'Cafe Chair Set of 4',
    price: 32999,
    image: 'https://images.unsplash.com/photo-1621277224630-81d9af65e40d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYWZlJTIwY2hhaXJ8ZW58MXx8fHwxNzM0OTc5ODM3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Commercial & Institutional',
    subcategory: 'Restaurant/Cafe',
    itemType: 'Cafe Chairs',
    description: 'Durable metal cafe chairs in set of 4. Stackable and easy to clean.',
    rating: 4.5,
    reviews: 98,
  },
  {
    id: '35',
    name: 'Restaurant Dining Table',
    price: 45999,
    image: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZXN0YXVyYW50JTIwdGFibGV8ZW58MXx8fHwxNzM0OTc5ODUyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Commercial & Institutional',
    subcategory: 'Restaurant/Cafe',
    itemType: 'Restaurant Tables',
    description: 'Commercial-grade restaurant table. Heavy-duty construction for high traffic.',
    rating: 4.7,
    reviews: 167,
  },

  // Interior & Decor Products
  {
    id: '36',
    name: 'LED Floor Lamp',
    price: 14999,
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmbG9vciUyMGxhbXB8ZW58MXx8fHwxNzM0OTc5ODY3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Interior & Decor Products',
    subcategory: 'Decor',
    itemType: 'Floor Lighting',
    description: 'Modern LED floor lamp with dimmer control. Energy-efficient and stylish.',
    rating: 4.6,
    reviews: 234,
  },
  {
    id: '37',
    name: 'Decorative Wall Mirror',
    price: 18999,
    image: 'https://images.unsplash.com/photo-1618220179428-22790b461013?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3YWxsJTIwbWlycm9yfGVufDF8fHx8MTczNDk3OTg4Mnww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Interior & Decor Products',
    subcategory: 'Decor',
    itemType: 'Mirrors',
    description: 'Ornate wall mirror with gold frame. Adds elegance to any room.',
    rating: 4.8,
    reviews: 156,
  },
  {
    id: '38',
    name: 'Luxury Curtain Set',
    price: 12999,
    image: 'https://images.unsplash.com/photo-1577961135991-2b0b5e8e4fbe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjdXJ0YWluc3xlbnwxfHx8fDE3MzQ5Nzk4OTd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'Interior & Decor Products',
    subcategory: 'Soft Furnishings',
    itemType: 'Curtains',
    description: 'Premium blackout curtains with elegant draping. Includes rod and fittings.',
    rating: 4.5,
    reviews: 189,
  },
];

export const categories = [
  { name: 'Living Room Furniture', icon: '🛋️', count: 8 },
  { name: 'Bedroom Furniture', icon: '🛏️', count: 6 },
  { name: 'Dining & Kitchen Furniture', icon: '🍽️', count: 6 },
  { name: 'Office & Study Furniture', icon: '💼', count: 10 },
  { name: 'Outdoor & Garden Furniture', icon: '🌳', count: 3 },
  { name: 'Commercial & Institutional', icon: '🏢', count: 2 },
  { name: 'Interior & Decor Products', icon: '✨', count: 3 },
];